config/routes.rb
Startupedia::Application.routes.draw do
  devise_for :users

  resources :startups

  get "static/home"

  get "static/about"

  root :to => 'static#home'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  	attr_accessible :description, :name

	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  		else
    		find(:all)
  		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

def resource_name
	:user
end

def resource
   	@resource ||= User.new
end

def devise_mapping
  	@devise_mapping ||= Devise.mappings[:user]
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]
  
  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @startups }
    end
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
    @startup = Startup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/new
  # GET /startups/new.json
  def new
    @startup = Startup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/1/edit
  def edit
    @startup = Startup.find(params[:id])
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(params[:startup])

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render json: @startup, status: :created, location: @startup }
      else
        format.html { render action: "new" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /startups/1
  # PUT /startups/1.json
  def update
    @startup = Startup.find(params[:id])

    respond_to do |format|
      if @startup.update_attributes(params[:startup])
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup = Startup.find(params[:id])
    @startup.destroy

    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "Startupedia", root_path, id: "logo", :class => "brand" %>

      <div class="nav-collapse">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li><%= link_to "Startups", startups_path %></li>
        </ul>
      </div>
      
      <nav>
        <ul class="nav pull-right">

          <!--About and divider-->
          <li><%= link_to "About", static_about_path %></li>
          <li class="divider-vertical"></li>

          <!--If user signed-in-->
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %>
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>My startups</li>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              </ul>

           <!--If user not signed-in-->
           <% else %>
           <li><%= link_to "Sign up", new_user_registration_path %></li>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Sign in
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">

                <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

                <div class="controls"><%= f.email_field :email, :type => "text", :style => "margin-bottom: 15px;", :placeholder => "Email" %></div>

                <div class="controls"><%= f.password_field :password, :type => "password", :style => "margin-bottom: 15px;", :placeholder => "Password" %></div>

                <% if devise_mapping.rememberable? -%>
                <div class="controls"><%= f.check_box :remember_me, :type => "checkbox", :style => "float: left; margin-right: 10px;" %> <%= f.label :remember_me %></div>
                <% end -%>
            
                <button class="btn btn-primary" style="clear: left; width: 100%; height: 32px; font-size: 13px;" type="submit"><%= f.submit "Sign in" %></button>
                <% end %>

              </ul> 
            <% end %>

          </li> 
        </ul>
      </nav>

    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/startups/_form.html.erb
<%= form_for @startup, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                startups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/startups/edit.html.erb
<%- model_class = @startup.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/startups/index.html.erb
<%- model_class = Startup.new.class -%>

<div class="row">
  <div class="span6 offset3">
    <div class="well">
      <%= form_tag startups_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %><br>
          <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= startup.name %></td>
        <td><%= startup.description %></td>
        <td><%=l startup.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_startup_path(startup), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      startup_path(startup),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_startup_path,
            :class => 'btn btn-primary' %>

app/views/startups/new.html.erb
<%- model_class = @startup.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/startups/show.html.erb
<%- model_class = @startup.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @startup.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:description) %>:</strong><br>
  <%= @startup.description %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              startups_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_startup_path(@startup), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              startup_path(@startup),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>